AWSTemplateFormatVersion: "2010-09-09"
Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-01fd08d7b0955d6d5"
      InstanceType: "t2.micro"
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      KeyName: "aws"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install docker -y
          systemctl start docker
          usermod -aG docker ec2-user
          aws s3 cp s3://calendartelebucket/chatbot ./chatbot
          cd ./chatbot
          docker run -v ./chatbot:./chatbot -d python:3.11-slim python3 ./chatbot/app.py
          #tar -xzf app.tar.gz
          #cd app
          #docker login -u ivshkvs -p dckr_pat_w1f9n80eI3PRBXwH_oQZszObTPQ
          #docker network create prometheus-network --driver bridge
          #docker run -d --network prometheus-network ivshkvs/tg_bot:latest
  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable SSH and Prometheus access"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: "9090"
          ToPort: "9090"
          CidrIp: "0.0.0.0/0"
