AWSTemplateFormatVersion: "2010-09-09"
Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-01fd08d7b0955d6d5"
      InstanceType: "t2.micro"
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      KeyName: "aws"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install docker -y
          systemctl start docker
          usermod -aG docker ec2-user
          docker login -u ivshkvs -p dckr_pat_w1f9n80eI3PRBXwH_oQZszObTPQ
          docker run -d -p 8000:8000 ivshkvs/tg_bot:latest
          docker run -d -p 9090:9090 prom/prometheus
  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable SSH and Prometheus access"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: "9090"
          ToPort: "9090"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: "8000"
          ToPort: "8000"
          CidrIp: "0.0.0.0/0"
