name: Create Server and Install Terraform

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        
    - name: Launch EC2 instance
      uses: aws-actions/amazon-ec2@v0.4.1
      with:
        image-id: ami-0c55b159cbfafe1f0 # Ubuntu 20.04 LTS
        instance-type: t2.micro
        user-data: |
          #!/bin/bash
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_linux_amd64.zip
          unzip terraform_1.1.0_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version
